name: Setup

runs:
  using: composite
  steps:
    - name: Install pnpm and Node.js
      uses: pnpm/setup@v1.0.0
      with:
        install: false
        cache: true

    - name: Install dependencies
      run: pnpm clean-install
      shell: bash
